# 0. Imports

In [1]:
import pandas as pd

# 1. Data Read In

In [2]:
df = pd.read_csv("../data/raw/labeled_data.csv")

In [3]:
df.head()

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,...,Mold_Temperature_3,Mold_Temperature_4,Mold_Temperature_5,Mold_Temperature_6,Mold_Temperature_7,Mold_Temperature_8,Mold_Temperature_9,Mold_Temperature_10,Mold_Temperature_11,Mold_Temperature_12
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,24.799999,27.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,...,24.799999,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 오전 12:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,25.000000,27.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7996 entries, 0 to 7995
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _id                       7996 non-null   str
 1   TimeStamp                 7996 non-null   str
 2   PART_FACT_PLAN_DATE       7996 non-null   str
 3   PART_FACT_SERIAL          7996 non-null   int64
 4   PART_NAME                 7996 non-null   str
 5   EQUIP_CD                  7996 non-null   str
 6   EQUIP_NAME                7996 non-null   str
 7   PassOrFail                7996 non-null   str
 8   Reason                    71 non-null     str
 9   Injection_Time            7996 non-null   float64
 10  Filling_Time              7996 non-null   float64
 11  Plasticizing_Time         7996 non-null   float64
 12  Cycle_Time                7996 non-null   float64
 13  Clamp_Close_Time          7996 non-null   float64
 14  Cushion_Position          7996 non-null   float64
 15  Switch_Over_Position      7996 non-null   float64
 16  Plasticizing_Position     7996 non-null   float64
 17  Clamp_Open_Position       7996 non-null   float64
 18  Max_Injection_Speed       7996 non-null   float64
 19  Max_Screw_RPM             7996 non-null   float64
 20  Average_Screw_RPM         7996 non-null   float64
 21  Max_Injection_Pressure    7996 non-null   float64
 22  Max_Switch_Over_Pressure  7996 non-null   float64
 23  Max_Back_Pressure         7996 non-null   float64
 24  Average_Back_Pressure     7996 non-null   float64
 25  Barrel_Temperature_1      7996 non-null   float64
 26  Barrel_Temperature_2      7996 non-null   float64
 27  Barrel_Temperature_3      7996 non-null   float64
 28  Barrel_Temperature_4      7996 non-null   float64
 29  Barrel_Temperature_5      7996 non-null   float64
 30  Barrel_Temperature_6      7996 non-null   float64
 31  Barrel_Temperature_7      7996 non-null   float64
 32  Hopper_Temperature        7996 non-null   float64
 33  Mold_Temperature_1        7996 non-null   float64
 34  Mold_Temperature_2        7996 non-null   float64
 35  Mold_Temperature_3        7996 non-null   float64
 36  Mold_Temperature_4        7996 non-null   float64
 37  Mold_Temperature_5        7996 non-null   float64
 38  Mold_Temperature_6        7996 non-null   float64
 39  Mold_Temperature_7        7996 non-null   float64
 40  Mold_Temperature_8        7996 non-null   float64
 41  Mold_Temperature_9        7996 non-null   float64
 42  Mold_Temperature_10       7996 non-null   float64
 43  Mold_Temperature_11       7996 non-null   float64
 44  Mold_Temperature_12       7996 non-null   float64
dtypes: float64(36), int64(1), str(8)
memory usage: 3.6 MB

# 2. Data Preprocessing

## 2.1. Dropping the columns that have only one unique value

In [5]:
# Check on the Unique value

df.nunique()

_id                         5232
TimeStamp                   2625
PART_FACT_PLAN_DATE           13
PART_FACT_SERIAL              17
PART_NAME                      6
EQUIP_CD                       3
EQUIP_NAME                     3
PassOrFail                     2
Reason                         3
Injection_Time                36
Filling_Time                  35
Plasticizing_Time            121
Cycle_Time                    48
Clamp_Close_Time              13
Cushion_Position              22
Switch_Over_Position           3
Plasticizing_Position         49
Clamp_Open_Position            5
Max_Injection_Speed           55
Max_Screw_RPM                 11
Average_Screw_RPM             16
Max_Injection_Pressure        35
Max_Switch_Over_Pressure      69
Max_Back_Pressure             68
Average_Back_Pressure         53
Barrel_Temperature_1          67
Barrel_Temperature_2          60
Barrel_Temperature_3          45
Barrel_Temperature_4          79
Barrel_Temperature_5          56
Barrel_Temperature_6          37
Barrel_Temperature_7           2
Hopper_Temperature            94
Mold_Temperature_1             1
Mold_Temperature_2             1
Mold_Temperature_3            56
Mold_Temperature_4            55
Mold_Temperature_5             1
Mold_Temperature_6             1
Mold_Temperature_7             1
Mold_Temperature_8             1
Mold_Temperature_9             1
Mold_Temperature_10            1
Mold_Temperature_11            1
Mold_Temperature_12            1
dtype: int64

In [6]:
# Mold_Temperature_s that have only one unique value are dropped

df.drop(
    columns=["Mold_Temperature_1", "Mold_Temperature_2", "Mold_Temperature_5", 
             "Mold_Temperature_6", "Mold_Temperature_7", "Mold_Temperature_8",
             "Mold_Temperature_9", "Mold_Temperature_10", "Mold_Temperature_11",
             "Mold_Temperature_12"],
    inplace=True
)

## 2.2. Removal of duplicated rows

In [7]:
# The number of unique _id is smaller than the number of rows --> Duplicated rows are removed

df.drop_duplicates(keep="first", inplace=True)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5232 entries, 0 to 5231
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _id                       5232 non-null   str
 1   TimeStamp                 5232 non-null   str
 2   PART_FACT_PLAN_DATE       5232 non-null   str
 3   PART_FACT_SERIAL          5232 non-null   int64
 4   PART_NAME                 5232 non-null   str
 5   EQUIP_CD                  5232 non-null   str
 6   EQUIP_NAME                5232 non-null   str
 7   PassOrFail                5232 non-null   str
 8   Reason                    60 non-null     str
 9   Injection_Time            5232 non-null   float64
 10  Filling_Time              5232 non-null   float64
 11  Plasticizing_Time         5232 non-null   float64
 12  Cycle_Time                5232 non-null   float64
 13  Clamp_Close_Time          5232 non-null   float64
 14  Cushion_Position          5232 non-null   float64
 15  Switch_Over_Position      5232 non-null   float64
 16  Plasticizing_Position     5232 non-null   float64
 17  Clamp_Open_Position       5232 non-null   float64
 18  Max_Injection_Speed       5232 non-null   float64
 19  Max_Screw_RPM             5232 non-null   float64
 20  Average_Screw_RPM         5232 non-null   float64
 21  Max_Injection_Pressure    5232 non-null   float64
 22  Max_Switch_Over_Pressure  5232 non-null   float64
 23  Max_Back_Pressure         5232 non-null   float64
 24  Average_Back_Pressure     5232 non-null   float64
 25  Barrel_Temperature_1      5232 non-null   float64
 26  Barrel_Temperature_2      5232 non-null   float64
 27  Barrel_Temperature_3      5232 non-null   float64
 28  Barrel_Temperature_4      5232 non-null   float64
 29  Barrel_Temperature_5      5232 non-null   float64
 30  Barrel_Temperature_6      5232 non-null   float64
 31  Barrel_Temperature_7      5232 non-null   float64
 32  Hopper_Temperature        5232 non-null   float64
 33  Mold_Temperature_3        5232 non-null   float64
 34  Mold_Temperature_4        5232 non-null   float64
dtypes: float64(26), int64(1), str(8)
memory usage: 2.0 MB

## 2.3. Change the time formate for the column, `PART_FACT_PLAN_DATE`

In [9]:
df["PART_FACT_PLAN_DATE"].unique()

<ArrowStringArray>
['2020-10-16 오전 12:00:00', '2020-10-20 오전 12:00:00', '2020-10-21 오전 12:00:00',
 '2020-10-22 오전 12:00:00', '2020-10-23 오전 12:00:00', '2020-10-27 오전 12:00:00',
 '2020-10-28 오전 12:00:00', '2020-10-29 오전 12:00:00', '2020-10-30 오전 12:00:00',
 '2020-11-03 오전 12:00:00', '2020-11-04 오전 12:00:00', '2020-11-05 오전 12:00:00',
 '2020-11-06 오전 12:00:00']
Length: 13, dtype: str

In [10]:
df["PART_FACT_PLAN_DATE"] = df["PART_FACT_PLAN_DATE"].str.replace("오전 12", "00")

In [11]:
df["PART_FACT_PLAN_DATE"].unique()

<ArrowStringArray>
['2020-10-16 00:00:00', '2020-10-20 00:00:00', '2020-10-21 00:00:00',
 '2020-10-22 00:00:00', '2020-10-23 00:00:00', '2020-10-27 00:00:00',
 '2020-10-28 00:00:00', '2020-10-29 00:00:00', '2020-10-30 00:00:00',
 '2020-11-03 00:00:00', '2020-11-04 00:00:00', '2020-11-05 00:00:00',
 '2020-11-06 00:00:00']
Length: 13, dtype: str

In [12]:
df

,_id,TimeStamp,PART_FACT_PLAN_DATE,PART_FACT_SERIAL,PART_NAME,EQUIP_CD,EQUIP_NAME,PassOrFail,Reason,Injection_Time,...,Barrel_Temperature_1,Barrel_Temperature_2,Barrel_Temperature_3,Barrel_Temperature_4,Barrel_Temperature_5,Barrel_Temperature_6,Barrel_Temperature_7,Hopper_Temperature,Mold_Temperature_3,Mold_Temperature_4
0,5f8928bb9c0189cc666ef19b,2020-10-16 04:57:47,2020-10-16 00:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,274.700012,274.799988,269.200012,255.000000,229.699997,0.0,66.300003,24.799999,27.500000
1,5f8928de9c0189cc666ef20b,2020-10-16 04:58:48,2020-10-16 00:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.600000
2,5f8928df9c0189cc666ef213,2020-10-16 04:58:48,2020-10-16 00:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.60,...,276.200012,275.500000,275.299988,270.799988,254.699997,229.500000,0.0,67.199997,24.799999,27.600000
3,5f8928f39c0189cc666ef25e,2020-10-16 04:59:48,2020-10-16 00:00:00,23,CN7 W/S SIDE MLD'G LH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.600000
4,5f8928f59c0189cc666ef265,2020-10-16 04:59:48,2020-10-16 00:00:00,24,CN7 W/S SIDE MLD'G RH,S14,650톤-우진2호기,Y,NaN,9.59,...,276.500000,275.000000,275.399994,271.100006,254.899994,230.000000,0.0,66.900002,25.000000,27.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5227,5fa23fbc9c0189cc66e44ddf,2020-11-04 05:43:29,2020-11-04 00:00:00,10,"RG3 MOLD'G W/SHLD, RH",S14,650톤-우진2호기,Y,NaN,1.07,...,285.899994,284.899994,285.700012,274.899994,265.000000,234.899994,0.0,64.500000,22.500000,24.299999
5228,5fa23fbd9c0189cc66e44de3,2020-11-04 05:43:29,2020-11-04 00:00:00,9,"RG3 MOLD'G W/SHLD, LH",S14,650톤-우진2호기,Y,NaN,1.07,...,285.899994,284.899994,285.700012,274.899994,265.000000,234.899994,0.0,64.500000,22.500000,24.299999
5229,5fa36afd9c0189cc66eebe41,2020-11-05 03:00:02,2020-11-05 00:00:00,3,"RG3 MOLD'G W/SHLD, LH",S14,650톤-우진2호기,Y,NaN,1.07,...,285.899994,284.899994,285.500000,274.399994,264.899994,235.100006,0.0,62.200001,22.299999,23.700001
5230,5fa36b009c0189cc66eebed7,2020-11-05 03:00:02,2020-11-05 00:00:00,4,"RG3 MOLD'G W/SHLD, RH",S14,650톤-우진2호기,Y,NaN,1.07,...,285.899994,284.899994,285.500000,274.399994,264.899994,235.100006,0.0,62.200001,22.299999,23.700001
5231,5fa4d0ce9c0189cc66fc7a13,2020-11-06 04:27:38,2020-11-06 00:00:00,7,"RG3 MOLD'G W/SHLD, LH",S14,650톤-우진2호기,Y,NaN,1.07,...,285.200012,285.600006,284.399994,275.500000,264.899994,234.899994,0.0,63.400002,21.900000,23.000000

## 2.4. Transformation of the values in `PassOrFail`

In [13]:
df["PassOrFail"].value_counts()

PassOrFail
Y    5172
N      60
Name: count, dtype: int64

In [14]:
# Change Y/N to 1/0

df["PassOrFail"] = df["PassOrFail"].apply(lambda x: 1 if x == "N" else 0)

# 3. Saving the preprocessed dataframe as csv

In [15]:
df.to_csv("../data/interim/labeled_data_preprocessed.csv", index=False)